### ISSUE TITLE
update the esp_plattform docs was: neopixels are ~not working. Or at least no one knows how to use them.

### ISSUE THREAD

**Issue by a2800276** [badgeteam/badgePython#24]

**Comment by smunaut** [comment]
Tested that yesterday and it seems to work
Doc is not correct though, I guess the API changed or something.

**Comment by a2800276** [comment]
Which docs? And which api did you test. 
(,I'm afraid we figured out how to access via python, documented it here https://www.badge.team/docs/badges/mch2022/software-development/micropython/neopixels/ and fixed a driver bug (https://github.com/badgeteam/esp32-component-ws2812/pull/2)

Please let me know where the docs are incorrect so I can update...

**Comment by smunaut** [comment]
Ah well, that doc ... but when I looked at it yesterday it wasn't saying that AFAIR. Or maybe I was looking somewhere else ...

**Comment by smunaut** [comment]
Ah no, I was looking at : https://www.badge.team/docs/esp32-platform-firmware/esp32-app-development/api-reference/neopixel/

**Comment by a2800276** [comment]
https://github.com/badgeteam/website/issues/76
